apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: april23-quarkus-2
  janus-idp.io/tekton: april23-quarkus-2
  backstage.io/kubernetes-id: april23-quarkus-2
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: april23-quarkus-2
resources:
  - application-dev.yaml