apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  labels:
    app.kubernetes.io/instance: april23-quarkus-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: april23-quarkus-2
    app.kubernetes.io/part-of: april23-quarkus-2
  name: april23-quarkus-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: april23-quarkus-2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: april23-quarkus-2
    spec:
      containers:
        - image: quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
          name: app-inference
          envFrom:
            - configMapRef:
                name: april23-quarkus-2-model-config
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
