apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: april23-quarkus-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: april23-quarkus-2
  name: april23-quarkus-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
