apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: april23-quarkus-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: april23-quarkus-2
  name: april23-quarkus-2
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: april23-quarkus-2
