apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: april23-quarkus-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/april23-quarkus-2:6deeb4d68908378f040f50ebdd4317c4230fb0d8@sha256:557fbed15ebd8ecdde6a038d0cc1858caccf85ecec6098d7216b7c3db7a69110 # use pre-built to bootstrap
          name: app-inference
